#!/usr/bin/env node
// Generates the @ikenga/tokens CSS distribution artifacts:
//   app-kit.css          — concatenation of src/app-kit/*.css (the component layer)
//   dist/tokens-css.js   — tokens.css   as `export default "<css>"`
//   dist/app-kit-css.js  — app-kit.css  as `export default "<css>"`
//
// Why the JS-string exports: no-build srcdoc pkgs cannot @import a stylesheet
// at runtime (WebKitGTK can't load subresources from about:srcdoc), so CSS
// rides the script path as a JS string and is injected as an inline <style>.
// JSON.stringify does the escaping in ONE deterministic call — the structural
// fix for the hand-escaped drift that produced the per-pkg tasks-css.js mirror.
//
// Usage: node scripts/build-css.mjs [--watch]

import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import { watch } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url))); // tokens/
const appKitDir = join(root, 'src', 'app-kit');
const distDir = join(root, 'dist');

const GENERATED = '/* GENERATED by scripts/build-css.mjs — do not edit by hand. */';

/** Concatenate src/app-kit/*.css (sorted) into the flat app-kit.css build output. */
async function concatAppKit() {
	let files = [];
	try {
		files = (await readdir(appKitDir)).filter((f) => f.endsWith('.css')).sort();
	} catch {
		files = []; // src/app-kit/ not created yet — still emit a valid (empty) layer
	}
	const parts = await Promise.all(
		files.map(
			async (f) => `\n/* ===== ${f} ===== */\n${await readFile(join(appKitDir, f), 'utf8')}`,
		),
	);
	const css = `${GENERATED}\n/* @ikenga/tokens app-kit — component layer; assumes tokens.css is loaded. */\n${parts.join('\n')}`;
	await writeFile(join(root, 'app-kit.css'), css);
	return { css, count: files.length };
}

/** Emit a CSS file as an ES module default-export string (for no-build pkgs). */
async function emitJsString(css, outName, sourceLabel) {
	await mkdir(distDir, { recursive: true });
	const body =
		`// GENERATED by scripts/build-css.mjs from ${sourceLabel}. Do not edit.\n` +
		`// No-build srcdoc pkgs import this and inject it as an inline <style>.\n` +
		`export default ${JSON.stringify(css)};\n`;
	await writeFile(join(distDir, outName), body);
}

async function build() {
	const tokensCss = await readFile(join(root, 'tokens.css'), 'utf8');
	const { css: appKitCss, count } = await concatAppKit();
	await emitJsString(tokensCss, 'tokens-css.js', 'tokens.css');
	await emitJsString(appKitCss, 'app-kit-css.js', 'src/app-kit/*.css');
	return count;
}

const count = await build();
console.log(
	`build-css: app-kit.css (${count} partial${count === 1 ? '' : 's'}) + dist/tokens-css.js + dist/app-kit-css.js`,
);

if (process.argv.includes('--watch')) {
	console.log('build-css: watching tokens.css + src/app-kit/ …');
	let timer = null;
	const rebuild = () => {
		clearTimeout(timer);
		timer = setTimeout(async () => {
			try {
				const n = await build();
				console.log(`build-css: rebuilt (${n} partials)`);
			} catch (err) {
				console.error('build-css: rebuild failed —', err.message);
			}
		}, 60);
	};
	try {
		watch(join(root, 'tokens.css'), rebuild);
		watch(appKitDir, { recursive: true }, rebuild);
	} catch (err) {
		console.error('build-css: watch unsupported here —', err.message);
	}
}
